// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2zkEb1WBoFwLryNfcj6AZxtaSvEJMLQ4',
    appId: '1:272198237449:web:2a235b890fd7bb40fa67d8',
    messagingSenderId: '272198237449',
    projectId: 'sealgonapp',
    authDomain: 'sealgonapp.firebaseapp.com',
    storageBucket: 'sealgonapp.firebasestorage.app',
    measurementId: 'G-S46ZB5BESM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBeHR0IOE6LyjMr-hz0_B_FmNbM0bChwA',
    appId: '1:272198237449:android:0762093480343e0dfa67d8',
    messagingSenderId: '272198237449',
    projectId: 'sealgonapp',
    storageBucket: 'sealgonapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0HFPSMSO7Qqj3hXSB3CTDl5VhGLlmm8g',
    appId: '1:272198237449:ios:d43dd982781245f7fa67d8',
    messagingSenderId: '272198237449',
    projectId: 'sealgonapp',
    storageBucket: 'sealgonapp.firebasestorage.app',
    iosBundleId: 'com.example.sealGonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0HFPSMSO7Qqj3hXSB3CTDl5VhGLlmm8g',
    appId: '1:272198237449:ios:d43dd982781245f7fa67d8',
    messagingSenderId: '272198237449',
    projectId: 'sealgonapp',
    storageBucket: 'sealgonapp.firebasestorage.app',
    iosBundleId: 'com.example.sealGonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2zkEb1WBoFwLryNfcj6AZxtaSvEJMLQ4',
    appId: '1:272198237449:web:af282afaffbe3e45fa67d8',
    messagingSenderId: '272198237449',
    projectId: 'sealgonapp',
    authDomain: 'sealgonapp.firebaseapp.com',
    storageBucket: 'sealgonapp.firebasestorage.app',
    measurementId: 'G-YPNPBV786X',
  );
}
